"""Community contribution flow for Money Mapper.

Enables users to contribute new merchant mappings to the public mapping database
via GitHub pull requests after passing privacy audit validation.
"""

import subprocess  # nosec B404
from datetime import datetime
from typing import Any

from money_mapper.privacy_audit import audit_merchant_name


def check_gh_cli_available() -> bool:
    """Check if GitHub CLI (gh) is available in the environment.

    Returns:
        bool: True if gh CLI is available, False otherwise
    """
    try:
        subprocess.run(  # nosec B603, B607
            ["gh", "--version"],
            capture_output=True,
            check=True,
            timeout=5,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        return False


def validate_merchant_for_community(merchant_name: str) -> dict[str, Any]:
    """Validate a merchant name for community contribution.

    Checks the merchant name against privacy audit standards to ensure
    it's safe to contribute publicly.

    Args:
        merchant_name: Name of merchant to validate

    Returns:
        dict: Validation result with keys:
            - passed (bool): Whether validation passed
            - score (int): Privacy risk score (0-100)
            - issues (list): List of detected issues if any
    """
    if not merchant_name or not merchant_name.strip():
        return {"passed": False, "score": 100, "issues": ["Empty merchant name"]}

    audit_result = audit_merchant_name(merchant_name)
    score = audit_result.get("score", 0)
    findings = audit_result.get("findings", [])
    issues = [f["reason"] for f in findings] if findings else []

    passed = score < 30

    return {
        "passed": passed,
        "score": score,
        "issues": issues,
    }


def format_mapping_entry(merchant: str, category: str, source: str) -> str:
    """Format a merchant mapping as a TOML entry.

    Args:
        merchant: Merchant name
        category: Category to map to
        source: Source of the mapping

    Returns:
        str: TOML-formatted entry ready for inclusion
    """
    # Escape quotes in merchant name
    escaped_merchant = merchant.replace('"', '\\"')
    escaped_source = source.replace('"', '\\"')

    entry = f'"{escaped_merchant}" = {{ category = "{category}", source = "{escaped_source}" }}'
    return entry


def generate_pr_template(merchant: str, category: str, source: str) -> dict[str, str]:
    """Generate a GitHub PR template for the merchant contribution.

    Args:
        merchant: Merchant name
        category: Category to map to
        source: Source of mapping (e.g., user transaction)

    Returns:
        dict: PR template with keys:
            - title: PR title
            - body: PR description
            - branch: Suggested branch name
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    branch_name = f"feature/merchant-contributions-{timestamp}"

    title = f"Add merchant mapping: {merchant} -> {category}"

    body = f"""# Community Contribution: Merchant Mapping

## Merchant Details
- **Name**: {merchant}
- **Category**: {category}
- **Source**: {source}

## TOML Entry
```toml
{format_mapping_entry(merchant, category, source)}
```

## Verification Checklist
- [ ] Merchant name is accurate
- [ ] Category is appropriate
- [ ] No PII or sensitive data exposed
- [ ] Privacy audit passed
- [ ] Mapping follows existing patterns

## Impact
This mapping will be added to the public merchant database and made available
to all Money Mapper users for automatic transaction categorization.

---
*Generated by Community Contribution Flow*
"""

    return {
        "title": title,
        "body": body,
        "branch": branch_name,
    }


def create_contribution_branch(branch_name: str) -> bool:
    """Create a git branch for the contribution.

    Args:
        branch_name: Name of the branch to create

    Returns:
        bool: True if successful, False otherwise
    """
    try:
        subprocess.run(
            ["git", "checkout", "-b", branch_name],
            check=True,
            capture_output=True,
            timeout=10,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        return False


def create_community_pr(template: dict[str, str]) -> tuple[str | None, str]:
    """Create a GitHub PR for the merchant mapping contribution.

    Args:
        template: PR template from generate_pr_template()

    Returns:
        tuple: (pr_url, error_output) where pr_url is the URL of the created PR or None
            if creation failed, and error_output is the captured error text on failure.
    """
    if not check_gh_cli_available():
        return None, "GitHub CLI (gh) is not installed"

    try:
        result = subprocess.run(  # nosec B603, B607
            [
                "gh",
                "pr",
                "create",
                "--title",
                template["title"],
                "--body",
                template["body"],
                "--label",
                "community-contribution",
            ],
            capture_output=True,
            text=True,
            timeout=15,
        )

        if result.returncode != 0:
            error_output = (result.stderr or result.stdout or "unknown error").strip()
            return None, error_output

        # Extract PR URL from output
        pr_url = result.stdout.strip()
        # Validate URL format before returning
        if pr_url and pr_url.startswith("https://github.com/"):
            return pr_url, ""
        return None, f"Unexpected output from gh pr create: {pr_url!r}"

    except subprocess.TimeoutExpired:
        return None, "gh pr create timed out after 15 seconds"
    except (FileNotFoundError, OSError) as exc:
        return None, str(exc)


def submit_community_contribution(merchant: str, category: str, source: str) -> dict[str, Any]:
    """Complete community contribution workflow.

    Validates merchant, creates branch, generates PR template, and submits PR.

    Args:
        merchant: Merchant name
        category: Category to map to
        source: Source of mapping

    Returns:
        dict: Result with keys:
            - success (bool): Whether complete flow succeeded
            - validation (dict): Validation result
            - pr_url (str): Created PR URL if successful
            - error (str): Error message if failed
    """
    validation = validate_merchant_for_community(merchant)

    if not validation["passed"]:
        return {
            "success": False,
            "validation": validation,
            "error": f"Merchant failed privacy audit: {validation['issues']}",
        }

    if not check_gh_cli_available():
        return {
            "success": False,
            "validation": validation,
            "error": (
                "GitHub CLI (gh) is not installed. Install it:\n"
                "  Windows: winget install --id GitHub.cli\n"
                "  macOS:   brew install gh\n"
                "  Linux:   See https://github.com/cli/cli/blob/trunk/docs/install_linux.md\n"
                "After installing, run: gh auth login"
            ),
        }

    auth_result = subprocess.run(  # nosec B603, B607
        ["gh", "auth", "status"], capture_output=True, text=True
    )
    if auth_result.returncode != 0:
        return {
            "success": False,
            "validation": validation,
            "error": "GitHub CLI is installed but not authenticated. Run: gh auth login",
        }

    template = generate_pr_template(merchant, category, source)
    branch_created = create_contribution_branch(template["branch"])

    if not branch_created:
        return {
            "success": False,
            "validation": validation,
            "error": f"Failed to create branch: {template['branch']}",
        }

    pr_url, error_output = create_community_pr(template)

    if not pr_url:
        return {
            "success": False,
            "validation": validation,
            "error": f"Failed to create GitHub PR: {error_output}",
        }

    return {
        "success": True,
        "validation": validation,
        "pr_url": pr_url,
    }
