name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the sections below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Configure settings in '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (Minor inconvenience)
        - Medium (Affects functionality)
        - High (Major feature broken)
        - Critical (Data loss/security issue)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Details about your environment
      value: |
        - OS: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
        - Python Version: [e.g., 3.11.5]
        - Money Mapper Version/Commit: [e.g., v1.0.0 or commit hash]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Copy and paste any relevant error messages or log output (redact sensitive info!)
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the problem
      placeholder: Add any other context here...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have redacted any sensitive/personal information from logs and descriptions
          required: true
        - label: I can reproduce this issue consistently
          required: false
