# Personal Financial Transaction Mappings - Template & Examples
# 
# This file contains YOUR specific merchant mappings and should be customized with your
# personal data like employers, local businesses, and banking patterns. These mappings
# have the HIGHEST priority and will override both merchant_mappings.toml and plaid_categories.toml.
#
# STRUCTURE:
# [PRIMARY_CATEGORY.DETAILED_CATEGORY]
# "your_specific_pattern" = { 
#     name = "Your Custom Name", 
#     category = "PRIMARY_CATEGORY", 
#     subcategory = "DETAILED_CATEGORY" 
# }
#
# ORGANIZATION:
# - Primary categories in alphabetical order (same as merchant_mappings.toml)
# - Detailed categories in alphabetical order within each primary category
# - Your patterns in alphabetical order within each detailed category
#
# PRIVACY NOTICE:
# - This file contains YOUR PERSONAL DATA
# - Remove all personal information before sharing publicly
# - Add this file to .gitignore if using version control
# - Keep backup copies of your customizations
#
# USAGE PRIORITY:
# 1. personal_mappings.toml (THIS FILE - highest priority)
# 2. merchant_mappings.toml (national chains - medium priority)
# 3. plaid_categories.toml (keyword fallback - lowest priority)

# ============================================================================
# EXAMPLES AND TEMPLATES
# ============================================================================
# 
# The sections below show examples of how to organize your personal mappings.
# Replace the example entries with your own specific data.
# Add new categories as needed - you don't need every category, only ones you use.

# ============================================================================
# FOOD_AND_DRINK - Your local restaurants and food places
# ============================================================================

[FOOD_AND_DRINK.FOOD_AND_DRINK_COFFEE]
# Your local coffee shops and cafes
# "your local coffee shop" = { name = "Main Street Coffee", category = "FOOD_AND_DRINK", subcategory = "FOOD_AND_DRINK_COFFEE" }
# "boundaries coffee" = { name = "Boundaries Coffee", category = "FOOD_AND_DRINK", subcategory = "FOOD_AND_DRINK_COFFEE" }

[FOOD_AND_DRINK.FOOD_AND_DRINK_FAST_FOOD]
# Regional chains and local fast food places not in merchant_mappings.toml
# "braums" = { name = "Braum's", category = "FOOD_AND_DRINK", subcategory = "FOOD_AND_DRINK_FAST_FOOD" }
# "kolache factory" = { name = "Kolache Factory", category = "FOOD_AND_DRINK", subcategory = "FOOD_AND_DRINK_FAST_FOOD" }
# "whataburger" = { name = "Whataburger", category = "FOOD_AND_DRINK", subcategory = "FOOD_AND_DRINK_FAST_FOOD" }

[FOOD_AND_DRINK.FOOD_AND_DRINK_RESTAURANT]
# Your local restaurants, family-owned places, and regional chains
# "your favorite restaurant" = { name = "Tony's Italian Kitchen", category = "FOOD_AND_DRINK", subcategory = "FOOD_AND_DRINK_RESTAURANT" }
# "local mexican place" = { name = "El Pueblo Authentic Mexican", category = "FOOD_AND_DRINK", subcategory = "FOOD_AND_DRINK_RESTAURANT" }
# "sushi place downtown" = { name = "Sakura Sushi Bar", category = "FOOD_AND_DRINK", subcategory = "FOOD_AND_DRINK_RESTAURANT" }

# ============================================================================
# GENERAL_SERVICES - Professional services you use
# ============================================================================

[GENERAL_SERVICES.GENERAL_SERVICES_AUTOMOTIVE]
# Your mechanic, car wash, oil change places
# "joe auto repair" = { name = "Joe's Auto Repair", category = "GENERAL_SERVICES", subcategory = "GENERAL_SERVICES_AUTOMOTIVE" }
# "main street car wash" = { name = "Main Street Car Wash", category = "GENERAL_SERVICES", subcategory = "GENERAL_SERVICES_AUTOMOTIVE" }

[GENERAL_SERVICES.GENERAL_SERVICES_INSURANCE]
# Your insurance companies and agents
# "progressive" = { name = "Progressive Insurance", category = "GENERAL_SERVICES", subcategory = "GENERAL_SERVICES_INSURANCE" }
# "state farm agent" = { name = "State Farm - John Smith", category = "GENERAL_SERVICES", subcategory = "GENERAL_SERVICES_INSURANCE" }

# ============================================================================
# GOVERNMENT_AND_NON_PROFIT - Your donations and government payments
# ============================================================================

[GOVERNMENT_AND_NON_PROFIT.GOVERNMENT_AND_NON_PROFIT_DONATIONS]
# Your church, charities, and regular donations
# "first baptist church" = { name = "First Baptist Church", category = "GOVERNMENT_AND_NON_PROFIT", subcategory = "GOVERNMENT_AND_NON_PROFIT_DONATIONS" }
# "united way" = { name = "United Way Donation", category = "GOVERNMENT_AND_NON_PROFIT", subcategory = "GOVERNMENT_AND_NON_PROFIT_DONATIONS" }
# "red cross" = { name = "American Red Cross", category = "GOVERNMENT_AND_NON_PROFIT", subcategory = "GOVERNMENT_AND_NON_PROFIT_DONATIONS" }

[GOVERNMENT_AND_NON_PROFIT.GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES]
# Your local government payments (city, county, state)
# "city of yourtown" = { name = "City of Yourtown", category = "GOVERNMENT_AND_NON_PROFIT", subcategory = "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES" }
# "county tax office" = { name = "Your County Tax Office", category = "GOVERNMENT_AND_NON_PROFIT", subcategory = "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES" }
# "dmv renewal" = { name = "DMV License Renewal", category = "GOVERNMENT_AND_NON_PROFIT", subcategory = "GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES" }

# ============================================================================
# INCOME - Your specific income sources (MOST IMPORTANT SECTION)
# ============================================================================

[INCOME.INCOME_WAGES]
# YOUR EMPLOYER(S) - This is the most important section to customize
# Replace these examples with your actual employer and payroll patterns
# 
# Common banking patterns for employers:
# - "des:dir dep your company" = direct deposit description
# - "des:direct dep your company" = direct deposit description  
# - "your company des:dir dep" = direct deposit description
# - "your company payroll" = payroll description
#
# EXAMPLES (replace with your actual employer):
# "des:dir dep your company name" = { name = "Your Company Name", category = "INCOME", subcategory = "INCOME_WAGES" }
# "des:direct dep your company" = { name = "Your Company Name", category = "INCOME", subcategory = "INCOME_WAGES" }
# "your company des:dir dep" = { name = "Your Company Name", category = "INCOME", subcategory = "INCOME_WAGES" }
# "your company payroll" = { name = "Your Company Name", category = "INCOME", subcategory = "INCOME_WAGES" }

[INCOME.INCOME_OTHER_INCOME]
# Side income, freelance work, rental income
# "freelance client name" = { name = "Freelance Work", category = "INCOME", subcategory = "INCOME_OTHER_INCOME" }
# "rental property llc" = { name = "Rental Property Income", category = "INCOME", subcategory = "INCOME_OTHER_INCOME" }

# ============================================================================
# LOAN_PAYMENTS - Your specific loan servicers and lenders
# ============================================================================

[LOAN_PAYMENTS.LOAN_PAYMENTS_CREDIT_CARD_PAYMENT]
# Your specific credit card payments (use bank name or card issuer)
# "chase credit card des:payment" = { name = "Chase Credit Card", category = "LOAN_PAYMENTS", subcategory = "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT" }
# "bank of america des:payment" = { name = "Bank of America Credit Card", category = "LOAN_PAYMENTS", subcategory = "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT" }
# "capital one autopay" = { name = "Capital One Credit Card", category = "LOAN_PAYMENTS", subcategory = "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT" }

[LOAN_PAYMENTS.LOAN_PAYMENTS_MORTGAGE_PAYMENT]
# Your mortgage company or loan servicer
# "your mortgage company" = { name = "ABC Mortgage Company", category = "LOAN_PAYMENTS", subcategory = "LOAN_PAYMENTS_MORTGAGE_PAYMENT" }
# "loancare des:payment" = { name = "LoanCare Mortgage Payment", category = "LOAN_PAYMENTS", subcategory = "LOAN_PAYMENTS_MORTGAGE_PAYMENT" }

[LOAN_PAYMENTS.LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT]
# Your student loan servicers
# "your loan servicer" = { name = "Your Student Loan Servicer", category = "LOAN_PAYMENTS", subcategory = "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT" }
# "nelnet des:payment" = { name = "Nelnet Student Loans", category = "LOAN_PAYMENTS", subcategory = "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT" }

# ============================================================================
# MEDICAL - Your healthcare providers
# ============================================================================

[MEDICAL.MEDICAL_DENTAL_CARE]
# Your dentist and dental care providers
# "your dentist name" = { name = "Dr. Smith Dentistry", category = "MEDICAL", subcategory = "MEDICAL_DENTAL_CARE" }
# "family dental care" = { name = "Family Dental Care", category = "MEDICAL", subcategory = "MEDICAL_DENTAL_CARE" }

[MEDICAL.MEDICAL_PRIMARY_CARE]
# Your doctors and medical providers
# "your doctor name" = { name = "Dr. Johnson Family Medicine", category = "MEDICAL", subcategory = "MEDICAL_PRIMARY_CARE" }
# "your medical group" = { name = "Your Medical Group", category = "MEDICAL", subcategory = "MEDICAL_PRIMARY_CARE" }

# ============================================================================
# PERSONAL_CARE - Your personal care providers
# ============================================================================

[PERSONAL_CARE.PERSONAL_CARE_HAIR_AND_BEAUTY]
# Your hair salon, barber, beauty services
# "your hair salon" = { name = "Main Street Hair Salon", category = "PERSONAL_CARE", subcategory = "PERSONAL_CARE_HAIR_AND_BEAUTY" }
# "your barber shop" = { name = "Joe's Barber Shop", category = "PERSONAL_CARE", subcategory = "PERSONAL_CARE_HAIR_AND_BEAUTY" }

[PERSONAL_CARE.PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS]
# Your gym or fitness center
# "your gym name" = { name = "Local Fitness Center", category = "PERSONAL_CARE", subcategory = "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS" }
# "yoga studio downtown" = { name = "Downtown Yoga Studio", category = "PERSONAL_CARE", subcategory = "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS" }

# ============================================================================
# RENT_AND_UTILITIES - Your specific utility providers
# ============================================================================

[RENT_AND_UTILITIES.RENT_AND_UTILITIES_GAS_AND_ELECTRICITY]
# Your electric and gas companies
# "your electric company" = { name = "Your Electric Company", category = "RENT_AND_UTILITIES", subcategory = "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY" }
# "your gas company" = { name = "Your Gas Company", category = "RENT_AND_UTILITIES", subcategory = "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY" }

[RENT_AND_UTILITIES.RENT_AND_UTILITIES_INTERNET_AND_CABLE]
# Your internet and cable providers
# "your internet provider" = { name = "Your Internet Provider", category = "RENT_AND_UTILITIES", subcategory = "RENT_AND_UTILITIES_INTERNET_AND_CABLE" }
# "your cable company" = { name = "Your Cable Company", category = "RENT_AND_UTILITIES", subcategory = "RENT_AND_UTILITIES_INTERNET_AND_CABLE" }

[RENT_AND_UTILITIES.RENT_AND_UTILITIES_RENT]
# Your landlord or property management company
# "your landlord name" = { name = "Your Landlord", category = "RENT_AND_UTILITIES", subcategory = "RENT_AND_UTILITIES_RENT" }
# "property management company" = { name = "ABC Property Management", category = "RENT_AND_UTILITIES", subcategory = "RENT_AND_UTILITIES_RENT" }

[RENT_AND_UTILITIES.RENT_AND_UTILITIES_TELEPHONE]
# Your cell phone carrier if different from merchant mappings
# "your cell carrier" = { name = "Your Cell Phone Carrier", category = "RENT_AND_UTILITIES", subcategory = "RENT_AND_UTILITIES_TELEPHONE" }

[RENT_AND_UTILITIES.RENT_AND_UTILITIES_WATER]
# Your water utility
# "your water department" = { name = "Your City Water Department", category = "RENT_AND_UTILITIES", subcategory = "RENT_AND_UTILITIES_WATER" }
# "city water services" = { name = "City Water Services", category = "RENT_AND_UTILITIES", subcategory = "RENT_AND_UTILITIES_WATER" }

# ============================================================================
# TRANSPORTATION - Your transportation providers
# ============================================================================

[TRANSPORTATION.TRANSPORTATION_GAS]
# Local or regional gas stations not in merchant mappings
# "local gas station" = { name = "Joe's Gas & Go", category = "TRANSPORTATION", subcategory = "TRANSPORTATION_GAS" }
# "regional chain gas" = { name = "Regional Gas Chain", category = "TRANSPORTATION", subcategory = "TRANSPORTATION_GAS" }

[TRANSPORTATION.TRANSPORTATION_TOLLS]
# Your local toll systems and transponders
# "your toll system" = { name = "Your Local Toll Authority", category = "TRANSPORTATION", subcategory = "TRANSPORTATION_TOLLS" }
# "your transponder" = { name = "Your Toll Transponder", category = "TRANSPORTATION", subcategory = "TRANSPORTATION_TOLLS" }

# ============================================================================
# IMPORTANT CUSTOMIZATION TIPS
# ============================================================================
#
# 1. INCOME SECTION IS MOST IMPORTANT:
#    - Your employer's direct deposit patterns are crucial for accurate categorization
#    - Check your bank statements for exact wording (e.g., "DES:DIR DEP COMPANY NAME")
#    - Add multiple variations if your employer's name appears differently
#
# 2. BANKING PATTERN EXAMPLES:
#    - Direct deposits: "des:dir dep", "des:direct dep", "directdep", "payroll"
#    - Credit card payments: "des:payment", "autopay", "online payment"
#    - Bank transfers: "online transfer", "ach transfer"
#
# 3. LOCAL BUSINESS TIPS:
#    - Use the name as it appears on your bank statement
#    - Some businesses show abbreviated names or include location codes
#    - Test patterns against actual transaction descriptions
#
# 4. TESTING YOUR PATTERNS:
#    - Run the parser in debug mode to see which patterns match
#    - Look for transactions with low confidence scores
#    - Add patterns for frequently unmatched transactions
#
# 5. MAINTENANCE:
#    - Review and update when you change jobs
#    - Add new local businesses as you discover them
#    - Remove patterns for businesses you no longer use
#
# 6. PRIVACY:
#    - Never share this file publicly with your actual data
#    - Consider using environment variables for sensitive patterns
#    - Keep backups of your customizations

# ============================================================================
# TEMPLATE FOR ADDING NEW CATEGORIES
# ============================================================================
# 
# If you need categories not shown above, follow this format:
#
# [PRIMARY_CATEGORY.DETAILED_CATEGORY]
# # Comment describing what goes in this category
# "your pattern" = { name = "Display Name", category = "PRIMARY_CATEGORY", subcategory = "DETAILED_CATEGORY" }
#
# Refer to plaid_categories.toml for the complete list of available categories.