# Money Mapper Settings Configuration
#
# This file contains configurable settings for the Money Mapper transaction parser.
# Modify these values to customize behavior without changing code.

[directories]
# Directory paths (relative to project root)
statements = "statements"        # Where PDF statements are stored
output = "output"               # Where processed files are saved
config = "config"               # Where configuration files are stored

[file_paths]
# Configuration file names (relative to config directory)
private_mappings = "private_mappings.toml"    # Personal/local merchant mappings
public_mappings = "public_mappings.toml"      # National chain merchant mappings
plaid_categories = "plaid_categories.toml"    # Plaid Personal Finance Categories
statement_patterns = "statement_patterns.toml" # PDF parsing patterns
settings = "settings.toml"                    # This settings file

# Input/output file names
new_mappings_template = "new_mappings.toml"   # Template for new mappings

[default_files]
# Default output file names (relative to output directory)
parsed_transactions = "financial_transactions.json"     # Raw parsed transactions
enriched_transactions = "enriched_transactions.json"    # Categorized transactions

[fuzzy_matching]
# Thresholds for fuzzy string matching (0.0 to 1.0)
enrichment_threshold = 0.7           # Minimum similarity for transaction enrichment
mapping_processor_threshold = 0.8    # Minimum similarity for mapping processor

[file_management]
# File management settings
backup_directory = "backups"         # Where backup files are stored

[processing]
# Processing behavior settings
auto_alphabetize = true              # Automatically sort mappings alphabetically
interactive_conflicts = true         # Enable interactive conflict resolution
validate_categories = true           # Validate categories against PFC taxonomy

[confidence_thresholds]
# Analysis confidence thresholds (0.0 to 1.0)
high_confidence = 0.8               # Threshold for high confidence categorization
medium_confidence = 0.5             # Threshold for medium confidence categorization

[display]
# Display and output formatting settings
max_examples_shown = 10             # Maximum number of examples to show in analysis

[privacy]
# Privacy and data redaction settings
enable_redaction = true              # Enable automatic redaction of sensitive data
redaction_mode = "fuzzy"             # "exact" or "fuzzy" matching for keywords
fuzzy_redaction_threshold = 0.85     # Minimum similarity for fuzzy keyword matching (0.0-1.0)

# Personal information to redact from transaction descriptions
# These will be replaced with generic placeholders using fuzzy matching
# Add your personal information here for privacy when sharing data
[privacy.keywords]
# Names to redact (will match variations like "John Smith", "JOHN SMITH", "Smith, John", etc.)
names = [
    # "John Smith",
    # "Jane Doe",
]

# Employers/companies to redact (will match company name variations)
employers = [
    # "Acme Corporation",
    # "XYZ Company",
]

# Locations to redact (cities, addresses, etc.)
locations = [
    # "123 Main Street",
    # "Springfield",
]

# Custom keywords to redact (any other sensitive terms)
custom = [
    # "my-bank-branch-name",
    # "doctor-office-name",
]

# Pattern-based redaction (regex patterns for structured data)
# These use exact pattern matching, not fuzzy matching
[privacy.patterns]
# Account numbers (already included by default)
# Format: { pattern = "regex", replacement = "placeholder", description = "what it matches" }
account_numbers = [
    { pattern = '''\b\d{4}\s*\d{4}\s*\d{4}\s*\d{4}\b''', replacement = '[ACCOUNT]', description = "16-digit account numbers" },
    { pattern = '''\b\d{4}\s*\d{4}\s*\d{4}\b''', replacement = '[ACCOUNT]', description = "12-digit account numbers" },
    { pattern = '''\bCHK\s+\d{4}(?:\s+\d{4})*''', replacement = 'CHK [ACCOUNT]', description = "Partial checking account numbers" },
]

# Personal identifiable information from ACH transactions
# NOTE: Process COID before INDN to avoid the INDN pattern eating the space before COID
pii_fields = [
    { pattern = '''COID:\d+''', replacement = 'COID:[COMPANY]', description = "Company IDs in ACH" },
    { pattern = '''INDN:[A-Z\s,\.]+?(?=\s+[A-Z]{3,}:|$)''', replacement = 'INDN:[NAME]', description = "Individual names in ACH" },
]

# Reference and tracking numbers
# NOTE: Process before account numbers to avoid long standalone numbers being caught
reference_numbers = [
    { pattern = '''\bID:\s*\d{7,}''', replacement = 'ID:[REF]', description = "Transaction IDs (7+ digits)" },
    { pattern = '''\b\d{12,}\b''', replacement = '[REF#]', description = "Long reference numbers (12+ digits, no spaces)" },
]

# Contact information
# NOTE: Phone pattern is more specific now to avoid matching other numeric IDs
contact_info = [
    { pattern = '''\b\d{3}[-]\d{3}[-]\d{4}\b''', replacement = '[PHONE]', description = "Phone numbers (dashed format)" },
    { pattern = '''\b\d{3}[.]\d{3}[.]\d{4}\b''', replacement = '[PHONE]', description = "Phone numbers (dotted format)" },
    { pattern = '''\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b''', replacement = '[EMAIL]', description = "Email addresses" },
]