# Statement Parsing Patterns and Detection Rules
# Configuration for PDF statement type detection and parsing

[detection.credit]
indicators = [
    "visa signature",
    "mastercard", 
    "credit card",
    "purchases and adjustments"
]
strong_indicators = {}
weight = 1

[detection.checking]
indicators = [
    "adv plus banking",
    "advantage plus", 
    "checking"
]
strong_indicators = { "your adv plus banking" = 5 }
weight = 1

[detection.savings]
indicators = [
    "regular savings",
    "savings account", 
    "your regular savings",
    "annual percentage yield",
    "interest earned"
]
strong_indicators = { "your regular savings" = 5 }
weight = 1

[account_patterns]
# Credit card pattern should be checked first (most specific - 4 sets of digits)
credit = '''Account #\s*(\d{4}\s+\d{4}\s+\d{4}\s+\d{4})'''
# Banking patterns (3 sets of digits)
checking = '''Account number:\s*(\d{4}\s+\d{4}\s+\d{4})'''
savings = '''Account number:\s*(\d{4}\s+\d{4}\s+\d{4})'''

[transaction_sections.checking]
# Match detail sections only (with "Date" header), not summary lines
# Matches from first "Date" after header through all "continued" sections until "Total"
deposits = '''Deposits and other additions\s*Date.*?(?=Total deposits and other additions)'''
withdrawals = '''Withdrawals and other subtractions\s*Date.*?(?=Total withdrawals and other subtractions)'''

[transaction_sections.savings]
deposits = '''Deposits and other additions.*?Total deposits and other additions'''
withdrawals = '''Other withdrawals.*?Total other withdrawals'''

[transaction_sections.credit]
# Bank of America credit card format: TRANS_DATE POST_DATE DESCRIPTION REF# ACCT# AMOUNT
# Pattern 1: Two dates (MM/DD MM/DD) - Standard BoA format with transaction + posting dates
#   - Captures reference number (group 4) and account suffix (group 5) separately
#   - These are excluded from the description to keep it clean
#   - Description now includes '/' to allow dates in descriptions (e.g., "CHECK-IN DATE 05/09/25")
# Pattern 2: Interest charges (MM/DD MM/DD DESCRIPTION AMOUNT) - No ref# or acct#
#   - Only matches lines containing "INTEREST CHARGED" to avoid false positives
#   - Interest charges don't have reference numbers in BoA statements
# NOTE: Old Pattern 2 (MM/DD/YYYY) and Pattern 3 (MM/DD fallback) removed
#       They were creating duplicate transactions by matching posting dates
patterns = [
    '''(\d{2}/\d{2})\s+(\d{2}/\d{2})\s+([A-Za-z0-9\*\-\'\s\.\,\(\)#/]+?)\s+(\d{4})\s+(\d{4})\s+(-?\d{1,3}(?:,\d{3})*\.\d{2})''',
    '''(\d{2}/\d{2})\s+(\d{2}/\d{2})\s+(INTEREST\s+CHARGED[^\d]*?)\s+(-?\d{1,3}(?:,\d{3})*\.\d{2})'''
]

[statement_period]
patterns = [
    '''for\s+([A-Za-z]+)\s+(\d{1,2}),?\s*(\d{4})\s+to\s+([A-Za-z]+)\s+(\d{1,2}),?\s*(\d{4})''',
    '''([A-Za-z]+)\s+(\d{1,2}),?\s*(\d{4})\s+to\s+([A-Za-z]+)\s+(\d{1,2}),?\s*(\d{4})''',
    '''(\d{1,2})/(\d{1,2})/(\d{2,4})\s+to\s+(\d{1,2})/(\d{1,2})/(\d{2,4})'''
]

[statement_period.month_names]
january = 1
february = 2
march = 3
april = 4
may = 5
june = 6
july = 7
august = 8
september = 9
october = 10
november = 11
december = 12

[text_sanitization]
patterns = [
    { pattern = '''\b\d{4}\s*\d{4}\s*\d{4}\s*\d{4}\b''', replacement = '[ACCOUNT]' },
    { pattern = '''\b\d{4}\s*\d{4}\s*\d{4}\b''', replacement = '[ACCOUNT]' },
    { pattern = '''\b\d{8,}\b''', replacement = '[REF#]' },
    { pattern = '''\b\d{3}[-.]?\d{3}[-.]?\d{4}\b''', replacement = '[PHONE]' },
    { pattern = '''\s+''', replacement = ' ' }
]